name: Deploy Slides to Pages
on:
  push:
    branches: [ main ]
    paths: [ "slides/**" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          cd slides
          npm ci
          npx reveal-md index.md --static _site
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/shef-04/pc-recommend-for-beginners.git
          git push origin gh-pages

permissions:
  contents: write